$('#headerServicesButton').hover(function() {
    $('#headerServices').toggleClass('display-n')
});
$('#headerServices').hover(function() {
    $(this).toggleClass('display-n')
    $('#headerAddress').addClass('display-n')
});

$('#headerAddressButton').hover(function() {
    $('#headerAddress').toggleClass('display-n')
});
$('#headerAddress').hover(function() {
    $(this).toggleClass('display-n')
    $('#headerServices').addClass('display-n')
});


$(function() {
    $('#menuCloseButton-1').css('transform', 'rotate(45deg)')
})
$('#menuCloseButton-1').on('click', function() {
    $(this).css('transform', 'rotate(45deg)')
    $('#menuCloseButton-2').css('transform', 'rotate(0deg)')
    $('#menuCloseButton-3').css('transform', 'rotate(0deg)')
    $('#menuItems-7').addClass('display-n')
    $('#menuItems-8').addClass('display-n')
    $('#menuItems-9').addClass('display-n')
    $('#menuItems-10').addClass('display-n')
    $('#menuItems-1').removeClass('display-n')
    $('#menuItems-2').removeClass('display-n')
    $('#menuItems-3').removeClass('display-n')
    $('#menuItems-4').removeClass('display-n')
    $('#menuItems-5').removeClass('display-n')
    $('#menuItems-6').removeClass('display-n')
    $('#menuItems-11').addClass('display-n')
    $('#menuItems-12').addClass('display-n')
    $('#menuItems-13').addClass('display-n')
})
$('#menuCloseButton-2').on('click', function() {
    $(this).css('transform', 'rotate(45deg)')
    $('#menuCloseButton-1').css('transform', 'rotate(0deg)')
    $('#menuCloseButton-3').css('transform', 'rotate(0deg)')
    $('#menuItems-7').removeClass('display-n')
    $('#menuItems-8').removeClass('display-n')
    $('#menuItems-9').removeClass('display-n')
    $('#menuItems-10').removeClass('display-n')
    $('#menuItems-1').addClass('display-n')
    $('#menuItems-2').addClass('display-n')
    $('#menuItems-3').addClass('display-n')
    $('#menuItems-4').addClass('display-n')
    $('#menuItems-5').addClass('display-n')
    $('#menuItems-6').addClass('display-n')
    $('#menuItems-11').addClass('display-n')
    $('#menuItems-12').addClass('display-n')
    $('#menuItems-13').addClass('display-n')
})
$('#menuCloseButton-3').on('click', function() {
    $(this).css('transform', 'rotate(45deg)')
    $('#menuCloseButton-1').css('transform', 'rotate(0deg)')
    $('#menuCloseButton-2').css('transform', 'rotate(0deg)')
    $('#menuItems-7').addClass('display-n')
    $('#menuItems-8').addClass('display-n')
    $('#menuItems-9').addClass('display-n')
    $('#menuItems-10').addClass('display-n')
    $('#menuItems-1').addClass('display-n')
    $('#menuItems-2').addClass('display-n')
    $('#menuItems-3').addClass('display-n')
    $('#menuItems-4').addClass('display-n')
    $('#menuItems-5').addClass('display-n')
    $('#menuItems-6').addClass('display-n')
    $('#menuItems-11').removeClass('display-n')
    $('#menuItems-12').removeClass('display-n')
    $('#menuItems-13').removeClass('display-n')
})
$('#menuCloseButtons-1').on('click', function() {
    $('#menuCloseButton-1').css('transform', 'rotate(45deg)')
    $('#menuCloseButton-2').css('transform', 'rotate(0deg)')
    $('#menuCloseButton-3').css('transform', 'rotate(0deg)')
    $('#menuItems-7').addClass('display-n')
    $('#menuItems-8').addClass('display-n')
    $('#menuItems-9').addClass('display-n')
    $('#menuItems-10').addClass('display-n')
    $('#menuItems-1').removeClass('display-n')
    $('#menuItems-2').removeClass('display-n')
    $('#menuItems-3').removeClass('display-n')
    $('#menuItems-4').removeClass('display-n')
    $('#menuItems-5').removeClass('display-n')
    $('#menuItems-6').removeClass('display-n')
    $('#menuItems-11').addClass('display-n')
    $('#menuItems-12').addClass('display-n')
    $('#menuItems-13').addClass('display-n')
})
$('#menuCloseButtons-2').on('click', function() {
    $('#menuCloseButton-2').css('transform', 'rotate(45deg)')
    $('#menuCloseButton-1').css('transform', 'rotate(0deg)')
    $('#menuCloseButton-3').css('transform', 'rotate(0deg)')
    $('#menuItems-7').removeClass('display-n')
    $('#menuItems-8').removeClass('display-n')
    $('#menuItems-9').removeClass('display-n')
    $('#menuItems-10').removeClass('display-n')
    $('#menuItems-1').addClass('display-n')
    $('#menuItems-2').addClass('display-n')
    $('#menuItems-3').addClass('display-n')
    $('#menuItems-4').addClass('display-n')
    $('#menuItems-5').addClass('display-n')
    $('#menuItems-6').addClass('display-n')
    $('#menuItems-11').addClass('display-n')
    $('#menuItems-12').addClass('display-n')
    $('#menuItems-13').addClass('display-n')
})
$('#menuCloseButtons-3').on('click', function() {
    $('#menuCloseButton-3').css('transform', 'rotate(45deg)')
    $('#menuCloseButton-1').css('transform', 'rotate(0deg)')
    $('#menuCloseButton-2').css('transform', 'rotate(0deg)')
    $('#menuItems-7').addClass('display-n')
    $('#menuItems-8').addClass('display-n')
    $('#menuItems-9').addClass('display-n')
    $('#menuItems-10').addClass('display-n')
    $('#menuItems-1').addClass('display-n')
    $('#menuItems-2').addClass('display-n')
    $('#menuItems-3').addClass('display-n')
    $('#menuItems-4').addClass('display-n')
    $('#menuItems-5').addClass('display-n')
    $('#menuItems-6').addClass('display-n')
    $('#menuItems-11').removeClass('display-n')
    $('#menuItems-12').removeClass('display-n')
    $('#menuItems-13').removeClass('display-n')
})