var wow = new WOW({mobile: false});
wow.init();



$('#headerServicesButton').hover(function() {
    $('#headerServices').toggleClass('display-n')
});
$('#headerServices').hover(function() {
    $(this).toggleClass('display-n')
    $('#headerAddress').addClass('display-n')
});

$('#headerAddressButton').hover(function() {
    $('#headerAddress').toggleClass('display-n')
});
$('#headerAddress').hover(function() {
    $(this).toggleClass('display-n')
    $('#headerServices').addClass('display-n')
});



$('#menuCloseButton-1').removeClass('rotate-45')
$('#menuCloseButton-2').removeClass('rotate-45')
$('#menuCloseButton-3').removeClass('rotate-45')
$('#menuCloseButton-4').removeClass('rotate-45')

$('#menuCloseButton-1').on('click', function() {
    $(this).toggleClass('rotate-45')
    $('#menuCloseButton-2').removeClass('rotate-45')
    $('#menuCloseButton-3').removeClass('rotate-45')
    $('#menuCloseButton-4').removeClass('rotate-45')
    $('#menuItems-7').addClass('display-n')
    $('#menuItems-8').addClass('display-n')
    $('#menuItems-9').addClass('display-n')
    $('#menuItems-10').addClass('display-n')
    $('#menuItems-1').toggleClass('display-n')
    $('#menuItems-2').toggleClass('display-n')
    $('#menuItems-3').toggleClass('display-n')
    $('#menuItems-4').toggleClass('display-n')
    $('#menuItems-5').toggleClass('display-n')
    $('#menuItems-6').toggleClass('display-n')
    $('#menuItems-11').addClass('display-n')
    $('#menuItems-12').addClass('display-n')
    $('#menuItems-13').addClass('display-n')
    $('#menuItems-14').addClass('display-n')
    $('#menuItems-15').addClass('display-n')
    $('#menuItems-16').addClass('display-n')
    $('#menuItems-17').addClass('display-n')
    $('#menuItems-18').addClass('display-n')
})
$('#menuCloseButton-2').on('click', function() {
    $(this).toggleClass('rotate-45')
    $('#menuCloseButton-1').removeClass('rotate-45')
    $('#menuCloseButton-3').removeClass('rotate-45')
    $('#menuCloseButton-4').removeClass('rotate-45')
    $('#menuItems-7').toggleClass('display-n')
    $('#menuItems-8').toggleClass('display-n')
    $('#menuItems-9').toggleClass('display-n')
    $('#menuItems-10').toggleClass('display-n')
    $('#menuItems-1').addClass('display-n')
    $('#menuItems-2').addClass('display-n')
    $('#menuItems-3').addClass('display-n')
    $('#menuItems-4').addClass('display-n')
    $('#menuItems-5').addClass('display-n')
    $('#menuItems-6').addClass('display-n')
    $('#menuItems-11').addClass('display-n')
    $('#menuItems-12').addClass('display-n')
    $('#menuItems-13').addClass('display-n')
    $('#menuItems-14').addClass('display-n')
    $('#menuItems-15').addClass('display-n')
    $('#menuItems-16').addClass('display-n')
    $('#menuItems-17').addClass('display-n')
    $('#menuItems-18').addClass('display-n')
})
$('#menuCloseButton-3').on('click', function() {
    $(this).toggleClass('rotate-45')
    $('#menuCloseButton-1').removeClass('rotate-45')
    $('#menuCloseButton-2').removeClass('rotate-45')
    $('#menuCloseButton-4').removeClass('rotate-45')
    $('#menuItems-7').addClass('display-n')
    $('#menuItems-8').addClass('display-n')
    $('#menuItems-9').addClass('display-n')
    $('#menuItems-10').addClass('display-n')
    $('#menuItems-1').addClass('display-n')
    $('#menuItems-2').addClass('display-n')
    $('#menuItems-3').addClass('display-n')
    $('#menuItems-4').addClass('display-n')
    $('#menuItems-5').addClass('display-n')
    $('#menuItems-6').addClass('display-n')
    $('#menuItems-11').toggleClass('display-n')
    $('#menuItems-12').toggleClass('display-n')
    $('#menuItems-13').addClass('display-n')
    $('#menuItems-14').addClass('display-n')
    $('#menuItems-15').addClass('display-n')
    $('#menuItems-16').addClass('display-n')
    $('#menuItems-17').addClass('display-n')
    $('#menuItems-18').addClass('display-n')
})
$('#menuCloseButton-4').on('click', function() {
    $(this).toggleClass('rotate-45')
    $('#menuCloseButton-1').removeClass('rotate-45')
    $('#menuCloseButton-3').removeClass('rotate-45')
    $('#menuCloseButton-2').removeClass('rotate-45')
    $('#menuItems-7').addClass('display-n')
    $('#menuItems-8').addClass('display-n')
    $('#menuItems-9').addClass('display-n')
    $('#menuItems-10').addClass('display-n')
    $('#menuItems-1').addClass('display-n')
    $('#menuItems-2').addClass('display-n')
    $('#menuItems-3').addClass('display-n')
    $('#menuItems-4').addClass('display-n')
    $('#menuItems-5').addClass('display-n')
    $('#menuItems-6').addClass('display-n')
    $('#menuItems-11').addClass('display-n')
    $('#menuItems-12').addClass('display-n')
    $('#menuItems-13').addClass('display-n')
    $('#menuItems-14').toggleClass('display-n')
    $('#menuItems-15').toggleClass('display-n')
    $('#menuItems-16').toggleClass('display-n')
    $('#menuItems-17').toggleClass('display-n')
    $('#menuItems-18').toggleClass('display-n')
})

$('#menuCloseButtons-1').on('click', function() {
    $('#menuCloseButton-1').toggleClass('rotate-45')
    $('#menuCloseButton-2').removeClass('rotate-45')
    $('#menuCloseButton-3').removeClass('rotate-45')
    $('#menuCloseButton-4').removeClass('rotate-45')
    $('#menuItems-7').addClass('display-n')
    $('#menuItems-8').addClass('display-n')
    $('#menuItems-9').addClass('display-n')
    $('#menuItems-10').addClass('display-n')
    $('#menuItems-1').toggleClass('display-n')
    $('#menuItems-2').toggleClass('display-n')
    $('#menuItems-3').toggleClass('display-n')
    $('#menuItems-4').toggleClass('display-n')
    $('#menuItems-5').toggleClass('display-n')
    $('#menuItems-6').toggleClass('display-n')
    $('#menuItems-11').addClass('display-n')
    $('#menuItems-12').addClass('display-n')
    $('#menuItems-13').addClass('display-n')
    $('#menuItems-14').addClass('display-n')
    $('#menuItems-15').addClass('display-n')
    $('#menuItems-16').addClass('display-n')
    $('#menuItems-17').addClass('display-n')
    $('#menuItems-18').addClass('display-n')
})
$('#menuCloseButtons-2').on('click', function() {
    $('#menuCloseButton-2').toggleClass('rotate-45')
    $('#menuCloseButton-1').removeClass('rotate-45')
    $('#menuCloseButton-3').removeClass('rotate-45')
    $('#menuCloseButton-4').removeClass('rotate-45')
    $('#menuItems-7').toggleClass('display-n')
    $('#menuItems-8').toggleClass('display-n')
    $('#menuItems-9').toggleClass('display-n')
    $('#menuItems-10').toggleClass('display-n')
    $('#menuItems-1').addClass('display-n')
    $('#menuItems-2').addClass('display-n')
    $('#menuItems-3').addClass('display-n')
    $('#menuItems-4').addClass('display-n')
    $('#menuItems-5').addClass('display-n')
    $('#menuItems-6').addClass('display-n')
    $('#menuItems-11').addClass('display-n')
    $('#menuItems-12').addClass('display-n')
    $('#menuItems-13').addClass('display-n')
    $('#menuItems-14').addClass('display-n')
    $('#menuItems-15').addClass('display-n')
    $('#menuItems-16').addClass('display-n')
    $('#menuItems-17').addClass('display-n')
    $('#menuItems-18').addClass('display-n')
})
$('#menuCloseButtons-3').on('click', function() {
    $('#menuCloseButton-3').toggleClass('rotate-45')
    $('#menuCloseButton-1').removeClass('rotate-45')
    $('#menuCloseButton-2').removeClass('rotate-45')
    $('#menuCloseButton-4').removeClass('rotate-45')
    $('#menuItems-7').addClass('display-n')
    $('#menuItems-8').addClass('display-n')
    $('#menuItems-9').addClass('display-n')
    $('#menuItems-10').addClass('display-n')
    $('#menuItems-1').addClass('display-n')
    $('#menuItems-2').addClass('display-n')
    $('#menuItems-3').addClass('display-n')
    $('#menuItems-4').addClass('display-n')
    $('#menuItems-5').addClass('display-n')
    $('#menuItems-6').addClass('display-n')
    $('#menuItems-11').toggleClass('display-n')
    $('#menuItems-12').toggleClass('display-n')
    $('#menuItems-13').addClass('display-n')
    $('#menuItems-14').addClass('display-n')
    $('#menuItems-15').addClass('display-n')
    $('#menuItems-16').addClass('display-n')
    $('#menuItems-17').addClass('display-n')
    $('#menuItems-18').addClass('display-n')
})
$('#menuCloseButtons-4').on('click', function() {
    $('#menuCloseButton-4').toggleClass('rotate-45')
    $('#menuCloseButton-1').removeClass('rotate-45')
    $('#menuCloseButton-3').removeClass('rotate-45')
    $('#menuCloseButton-2').removeClass('rotate-45')
    $('#menuItems-7').addClass('display-n')
    $('#menuItems-8').addClass('display-n')
    $('#menuItems-9').addClass('display-n')
    $('#menuItems-10').addClass('display-n')
    $('#menuItems-1').addClass('display-n')
    $('#menuItems-2').addClass('display-n')
    $('#menuItems-3').addClass('display-n')
    $('#menuItems-4').addClass('display-n')
    $('#menuItems-5').addClass('display-n')
    $('#menuItems-6').addClass('display-n')
    $('#menuItems-11').addClass('display-n')
    $('#menuItems-12').addClass('display-n')
    $('#menuItems-13').addClass('display-n')
    $('#menuItems-14').toggleClass('display-n')
    $('#menuItems-15').toggleClass('display-n')
    $('#menuItems-16').toggleClass('display-n')
    $('#menuItems-17').toggleClass('display-n')
    $('#menuItems-18').toggleClass('display-n')
})
